---
title: "Beispiel 5.2.2"
author: "Bernd Gruber"
date: 2022-12-20
output:
  pdf_document: default
  html_document:
    self_contained: no
    df_print: paged
editor_options:
  chunk_output_type: inline
  markdown: 
    wrap: 72
---

# Totalerfassung homogene Untersuchungsflaechen

Notwendige Eingabeparameter:

* TF: Anzahl der Teilflaechen
* t: Anzahl der Probeflaechen
* $n_i$: Anzahl gefundener Individuen auf Probeflaeche i [as a vector]


```{r, echo=FALSE}
#Funktionen
#geschaetzte Anzahl estN
est.N<- function(TF,funde) {
	return(TF/sum(funde$anz_probeflaechen) * sum(funde$anz_probeflaechen*funde$anz_funde))
}


var.N <- function(TF,funde, conf=0.9) {
	t <- funde$anz_probeflaechen
	n <- funde$anz_funde
	
	mean.n <- sum(n*t)/sum(t)
	s2 <- sum(((n-mean.n)^2)*t)/ (sum(t)-1)
	var.N <-  TF^2*s2/sum(t)*(1-sum(t)/TF)
	est.N <- round(est.N(TF,funde))
	tv <- qt((1-conf)/2, sum(t)-1, lower.tail = F)
	ci <- round(tv*sqrt(var.N))
	N.low <- est.N - ci
	N.up <- est.N + ci 
	res <- paste0("Geschaetzte Anzahl von Funden:\n est(N): ", round(est.N),"\n Var(N): ",round(var.N,2), "\n Konfidenzinterval(N)[",conf*100,"%]: ",N.low," - ", N.up )
	cat(res)
	return(list(N=est.N, var.N=round(var.N,2), N.low=N.low, N.up=N.up))
}

```


Beispiel anhand Fischotterspuren im Schnee 
```{r}


funde <- data.frame(anz_funde=c(0,1,2), anz_probeflaechen=c(45,4,1))
funde


est.N(TF=514, funde = funde)

erg1 <- var.N(TF=514, funde=funde, conf=0.9)
erg2 <- var.N(TF=514, funde=funde, conf=0.95)


```
